config/routes.rb
Rails.application.routes.draw do
  get "sign-up", to: "users#new", as: :sign_up
  post "sign-up", to: "users#sign_up"
  get "new-password", to: "users#new_password", as: :new_password
  post "users", to: "users#create"
  get "dashboard", to: "users#show", as: :dashboard
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :current_user

  def require_user
    redirect_to root_path unless current_user
  end

  def redirect_user
    redirect_to dashboard_path if current_user
  end

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_user, except: %i[ show ]
  before_action :require_user, only: %i[ show ]

  def new
    @user = User.new
  end

  def sign_up
    @user = User.find_or_initialize_by(email: user_params[:email])
    if @user.new_record?
      session[:email] = @user.email
      redirect_to new_password_path
    else
      flash[:error] = "Something went wrong."
      render :new
    end
  end

  def new_password
    @user = User.find_or_initialize_by(email: session[:email])
  end

  def create
    @user = User.find_or_initialize_by(email: session[:email]).tap do |user|
      user.password = user_params[:password]
      user.password_confirmation = user_params[:password_confirmation]
    end
    if @user.save
      session[:email] = nil
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash[:error] = "Something went wrong."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Whimsical Odyssey" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Hello, world!</h1>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_with model: @user, url: sign_up_path do |form| %>
  <%= form.label :email, class: "form-label" %>
  <%= form.text_field :email, class: "form-control" %>
  <%= form.submit "Continue", class: "btn btn-primary" %>
<% end %>

app/views/users/new_password.html.erb
<%= form_with model: @user, url: users_path do |form| %>
  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit "Continue" %>
<% end %>